# Ruby 3.4.8 のイメージを取得
FROM ruby:3.4.8

# 必要なパッケージをインストール
RUN apt-get update -qq && apt-get install -y \
    default-mysql-client \
    build-essential \
    default-libmysqlclient-dev \
    imagemagick \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

# アプリケーションディレクトリを作成
WORKDIR /back

# GemfileとGemfile.lockをコピーしてbundle install
COPY ./Gemfile ./Gemfile.lock ./
RUN bundle install

# アプリケーションコードを.(/back/)にコピー
COPY . .