# Node.jsのActive ltsである24.12.0
FROM node:24.12.0

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y libc6-dev git curl dotenv && apt-get clean

# アプリケーションディレクトリを作成
WORKDIR /front

# package.jsonとyarn.lockをコピーしてyarn install
COPY ./package.json ./yarn.lock ./
RUN yarn install

# アプリケーションコードを.(/front/)にコピー
COPY . .